import type { MappingRule } from './types';

// Default SYSCOHADA/OHADA mapping rules
// Based on the SYSCOHADA Révisé chart of accounts

export const DEFAULT_MAPPING_RULES: MappingRule[] = [

  // ─── ACTIF – Immobilisations incorporelles ────────────────────────────────
  {
    id: 'ACTIF_IMMO_INC_GROSS',
    report_type: 'ACTIF',
    report_section: 'IMMO_INC',
    report_line_code: 'IMMO_INC_GROSS',
    label_fr: 'Immobilisations incorporelles (brut)',
    label_en: 'Intangible assets (gross)',
    account_prefixes: ['20', '21', '22'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 100,
    is_required: true,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_IMMO_INC_DEPR',
    report_type: 'ACTIF',
    report_section: 'IMMO_INC',
    report_line_code: 'IMMO_INC_DEPR',
    label_fr: 'Amortissements immobilisations incorporelles',
    label_en: 'Depreciation of intangible assets',
    account_prefixes: ['280', '281', '282'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'subtract_from_gross',
    display_order: 101,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Immobilisations corporelles ──────────────────────────────────
  {
    id: 'ACTIF_IMMO_CORP_GROSS',
    report_type: 'ACTIF',
    report_section: 'IMMO_CORP',
    report_line_code: 'IMMO_CORP_GROSS',
    label_fr: 'Immobilisations corporelles (brut)',
    label_en: 'Tangible fixed assets (gross)',
    account_prefixes: ['23', '24', '25', '26', '27'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 200,
    is_required: true,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_IMMO_CORP_DEPR',
    report_type: 'ACTIF',
    report_section: 'IMMO_CORP',
    report_line_code: 'IMMO_CORP_DEPR',
    label_fr: 'Amortissements immobilisations corporelles',
    label_en: 'Depreciation of tangible fixed assets',
    account_prefixes: ['283', '284', '285', '286', '287'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'subtract_from_gross',
    display_order: 201,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Immobilisations financières ──────────────────────────────────
  {
    id: 'ACTIF_IMMO_FIN_GROSS',
    report_type: 'ACTIF',
    report_section: 'IMMO_FIN',
    report_line_code: 'IMMO_FIN_GROSS',
    label_fr: 'Immobilisations financières (brut)',
    label_en: 'Financial assets (gross)',
    account_prefixes: ['271', '272', '273', '274', '275', '276', '277', '278'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 300,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_IMMO_FIN_PROV',
    report_type: 'ACTIF',
    report_section: 'IMMO_FIN',
    report_line_code: 'IMMO_FIN_PROV',
    label_fr: 'Provisions immobilisations financières',
    label_en: 'Provisions for financial assets',
    account_prefixes: ['297'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'subtract_from_gross',
    display_order: 301,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Stocks ───────────────────────────────────────────────────────
  {
    id: 'ACTIF_STOCKS',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'STOCKS',
    label_fr: 'Stocks et en-cours',
    label_en: 'Inventories and work-in-progress',
    account_prefixes: ['31', '32', '33', '34', '35', '36', '37', '38'],
    excluded_accounts: [],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 400,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_STOCKS_PROV',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'STOCKS_PROV',
    label_fr: 'Provisions pour dépréciation des stocks',
    label_en: 'Provisions for inventory depreciation',
    account_prefixes: ['39'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'subtract_from_gross',
    display_order: 401,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Créances clients ─────────────────────────────────────────────
  {
    id: 'ACTIF_CREANCES_CLIENTS',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'CREANCES_CLIENTS',
    label_fr: 'Créances clients',
    label_en: 'Customer receivables',
    account_prefixes: ['411', '412', '413', '414', '415', '416', '417', '418'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 500,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_CREANCES_CLIENTS_PROV',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'CREANCES_CLIENTS_PROV',
    label_fr: 'Provisions créances clients',
    label_en: 'Provisions for customer receivables',
    account_prefixes: ['491'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'subtract_from_gross',
    display_order: 501,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Autres créances ──────────────────────────────────────────────
  {
    id: 'ACTIF_AUTRES_CREANCES',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'AUTRES_CREANCES',
    label_fr: 'Autres créances',
    label_en: 'Other receivables',
    account_prefixes: ['45', '47', '48'],
    excluded_accounts: ['478', '479'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 600,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── ACTIF – Trésorerie actif ─────────────────────────────────────────────
  {
    id: 'ACTIF_BANQUES',
    report_type: 'ACTIF',
    report_section: 'TRESORERIE_ACTIF',
    report_line_code: 'BANQUES_ACTIF',
    label_fr: 'Banques, chèques postaux, caisse',
    label_en: 'Banks, postal cheques, cash',
    account_prefixes: ['521', '522', '523', '524', '525', '531', '532', '533'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 700,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_AVANCES_FOURNISSEURS',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'AVANCES_FOURNISSEURS',
    label_fr: 'Fournisseurs debiteurs, avances et acomptes',
    label_en: 'Supplier advances and deposits',
    account_prefixes: ['409'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 530,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_PERSONNEL_CREANCES',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'PERSONNEL_CREANCES',
    label_fr: 'Personnel et organismes sociaux debiteurs',
    label_en: 'Personnel and social receivables',
    account_prefixes: ['421', '422', '423', '424', '425', '426', '427', '428', '431', '432', '433', '434', '435'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 540,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_ETAT_CREANCES',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'ETAT_CREANCES',
    label_fr: 'Etat et collectivites publiques debiteurs',
    label_en: 'Tax and public receivables',
    account_prefixes: ['441', '442', '443', '444', '445', '446', '447', '448'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 550,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_ASSOCIES_CREANCES',
    report_type: 'ACTIF',
    report_section: 'ACTIF_CIRC',
    report_line_code: 'ASSOCIES_CREANCES',
    label_fr: 'Associes et comptes courants debiteurs',
    label_en: 'Shareholder receivables',
    account_prefixes: ['46'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 560,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_CAISSE',
    report_type: 'ACTIF',
    report_section: 'TRESORERIE_ACTIF',
    report_line_code: 'CAISSE_ACTIF',
    label_fr: 'Caisse',
    label_en: 'Cash on hand',
    account_prefixes: ['571', '572', '573', '574'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 701,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_MOBILE_MONEY',
    report_type: 'ACTIF',
    report_section: 'TRESORERIE_ACTIF',
    report_line_code: 'MOBILE_MONEY_ACTIF',
    label_fr: 'Monnaie electronique et tresorerie mobile',
    label_en: 'Mobile money and electronic cash',
    account_prefixes: ['55'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 703,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'ACTIF_TITRES_PLACEMENT',
    report_type: 'ACTIF',
    report_section: 'TRESORERIE_ACTIF',
    report_line_code: 'TITRES_PLACEMENT',
    label_fr: 'Titres de placement',
    label_en: 'Short-term investments',
    account_prefixes: ['50', '51'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 702,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── PASSIF – Capitaux propres ─────────────────────────────────────────────
  {
    id: 'PASSIF_CAPITAL',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'CAPITAL',
    label_fr: 'Capital',
    label_en: 'Capital',
    account_prefixes: ['101', '102', '103', '104', '105', '106'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1000,
    is_required: true,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_RESERVES',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'RESERVES',
    label_fr: 'Réserves',
    label_en: 'Reserves',
    account_prefixes: ['111', '112', '113', '114', '115', '116', '117', '118'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1001,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_REPORT_NOUVEAU',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'REPORT_NOUVEAU',
    label_fr: 'Report à nouveau',
    label_en: 'Retained earnings',
    account_prefixes: ['12'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1002,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_RESULTAT_NET',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'RESULTAT_NET_BILAN',
    label_fr: 'Résultat net de l\'exercice',
    label_en: 'Net result for the period',
    account_prefixes: ['13'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1003,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_SUBV_INVEST',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'SUBV_INVEST',
    label_fr: 'Subventions d\'investissement',
    label_en: 'Investment grants',
    account_prefixes: ['14'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1004,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_PROV_REGL',
    report_type: 'PASSIF',
    report_section: 'CAPITAUX_PROPRES',
    report_line_code: 'PROV_REGL',
    label_fr: 'Provisions réglementées',
    label_en: 'Regulated provisions',
    account_prefixes: ['15'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1005,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── PASSIF – Dettes financières ──────────────────────────────────────────
  {
    id: 'PASSIF_EMPRUNTS',
    report_type: 'PASSIF',
    report_section: 'DETTES_FIN',
    report_line_code: 'EMPRUNTS',
    label_fr: 'Emprunts et dettes financières',
    label_en: 'Loans and financial debts',
    account_prefixes: ['16', '17'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1100,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_PROV_FIN',
    report_type: 'PASSIF',
    report_section: 'DETTES_FIN',
    report_line_code: 'PROV_FIN',
    label_fr: 'Provisions financières pour risques et charges',
    label_en: 'Financial provisions for risks and charges',
    account_prefixes: ['19'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1101,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── PASSIF – Dettes d'exploitation ──────────────────────────────────────
  {
    id: 'PASSIF_FOURNISSEURS',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'FOURNISSEURS',
    label_fr: 'Fournisseurs et comptes rattachés',
    label_en: 'Suppliers and related accounts',
    account_prefixes: ['401', '402', '403', '404', '405', '406', '407', '408'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1200,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_DETTES_FISCALES',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'DETTES_FISCALES',
    label_fr: 'Dettes fiscales',
    label_en: 'Tax liabilities',
    account_prefixes: ['441', '442', '443', '444', '445', '446', '447', '448'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1201,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_DETTES_SOCIALES',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'DETTES_SOCIALES',
    label_fr: 'Dettes sociales et envers le personnel',
    label_en: 'Social and personnel liabilities',
    account_prefixes: ['421', '422', '423', '424', '425', '426', '427', '428', '431', '432', '433', '434', '435'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1202,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_AUTRES_DETTES',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'AUTRES_DETTES',
    label_fr: 'Autres dettes',
    label_en: 'Other liabilities',
    account_prefixes: ['47', '48'],
    excluded_accounts: ['478', '479'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1203,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── PASSIF – Trésorerie passif ───────────────────────────────────────────
  {
    id: 'PASSIF_BANQUES_CREDIT',
    report_type: 'PASSIF',
    report_section: 'TRESORERIE_PASSIF',
    report_line_code: 'BANQUES_CREDIT',
    label_fr: 'Banques, crédits de trésorerie, découverts',
    label_en: 'Bank overdrafts and short-term credit',
    account_prefixes: ['561', '562', '563', '564', '565'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1300,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_AVANCES_CLIENTS',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'AVANCES_CLIENTS',
    label_fr: 'Clients crediteurs, avances et acomptes',
    label_en: 'Customer advances and deposits',
    account_prefixes: ['419'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1204,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_ASSOCIES_DETTES',
    report_type: 'PASSIF',
    report_section: 'PASSIF_CIRC',
    report_line_code: 'ASSOCIES_DETTES',
    label_fr: 'Associes et comptes courants crediteurs',
    label_en: 'Shareholder payables',
    account_prefixes: ['46'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1205,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_MOBILE_MONEY_CREDIT',
    report_type: 'PASSIF',
    report_section: 'TRESORERIE_PASSIF',
    report_line_code: 'MOBILE_MONEY_PASSIF',
    label_fr: 'Monnaie electronique et tresorerie mobile creditrice',
    label_en: 'Mobile money and electronic cash liabilities',
    account_prefixes: ['55'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1302,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── COMPTE RÉSULTAT – Produits d'exploitation ───────────────────────────
  {
    id: 'CR_CHIFFRE_AFFAIRES',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'CHIFFRE_AFFAIRES',
    label_fr: 'Chiffre d\'affaires',
    label_en: 'Turnover',
    account_prefixes: ['70'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2000,
    is_required: true,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_PROD_STOCKEE',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'PROD_STOCKEE',
    label_fr: 'Production stockée ou déstockée',
    label_en: 'Change in inventory of finished goods',
    account_prefixes: ['71'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2001,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_PROD_IMMO',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'PROD_IMMO',
    label_fr: 'Production immobilisée',
    label_en: 'Capitalized production',
    account_prefixes: ['72'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2002,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_AUTRES_PROD_EXPLOIT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'AUTRES_PROD_EXPLOIT',
    label_fr: 'Autres produits d\'exploitation',
    label_en: 'Other operating income',
    account_prefixes: ['73', '74', '75'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2003,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_REPRISES_PROV',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'REPRISES_PROV',
    label_fr: 'Reprises de provisions et amortissements',
    label_en: 'Reversals of provisions and depreciation',
    account_prefixes: ['76', '78', '79'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2004,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── COMPTE RÉSULTAT – Charges d'exploitation ────────────────────────────
  {
    id: 'CR_ACHATS',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'ACHATS',
    label_fr: 'Achats de marchandises et matières',
    label_en: 'Purchases of goods and materials',
    account_prefixes: ['60'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2100,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_SERVICES_EXT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'SERVICES_EXT',
    label_fr: 'Services extérieurs',
    label_en: 'External services',
    account_prefixes: ['61', '62', '63'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2101,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_IMPOTS_TAXES',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'IMPOTS_TAXES',
    label_fr: 'Impôts et taxes',
    label_en: 'Taxes and duties',
    account_prefixes: ['64'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2102,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_CHARGES_PERS',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'CHARGES_PERS',
    label_fr: 'Charges de personnel',
    label_en: 'Personnel expenses',
    account_prefixes: ['66'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2103,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_AUTRES_CHARGES_EXPLOIT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'AUTRES_CHARGES_EXPLOIT',
    label_fr: 'Autres charges d\'exploitation',
    label_en: 'Other operating expenses',
    account_prefixes: ['65'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2104,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_DOTATIONS_AMORT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'DOTATIONS_AMORT',
    label_fr: 'Dotations aux amortissements et provisions',
    label_en: 'Depreciation and provisions expenses',
    account_prefixes: ['68'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2105,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── COMPTE RÉSULTAT – Résultat financier ────────────────────────────────
  {
    id: 'CR_PROD_FIN',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'RESULTAT_FIN',
    report_line_code: 'PROD_FIN',
    label_fr: 'Revenus financiers',
    label_en: 'Financial income',
    account_prefixes: ['77'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2200,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_CHARGES_FIN',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'RESULTAT_FIN',
    report_line_code: 'CHARGES_FIN',
    label_fr: 'Frais financiers et charges assimilées',
    label_en: 'Financial expenses and related charges',
    account_prefixes: ['67'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2201,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── COMPTE RÉSULTAT – HAO ────────────────────────────────────────────────
  {
    id: 'CR_PROD_HAO',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'RESULTAT_HAO',
    report_line_code: 'PROD_HAO',
    label_fr: 'Produits HAO',
    label_en: 'Non-ordinary income',
    account_prefixes: ['82', '84', '86', '88'],
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 2300,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_CHARGES_HAO',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'RESULTAT_HAO',
    report_line_code: 'CHARGES_HAO',
    label_fr: 'Charges HAO',
    label_en: 'Non-ordinary expenses',
    account_prefixes: ['81', '83', '85', '87'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2301,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // ─── COMPTE RÉSULTAT – Impôt sur le résultat ─────────────────────────────
  {
    id: 'CR_IMPOT_RESULTAT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'IMPOT',
    report_line_code: 'IMPOT_RESULTAT',
    label_fr: 'Impôts sur le résultat',
    label_en: 'Income tax',
    account_prefixes: ['69'],
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 2400,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // Conversion differences used by the workbook sheet VENTI DES ECARTS DE CONV.
  {
    id: 'ACTIF_ECART_CONV_ACTIF',
    report_type: 'ACTIF',
    report_section: 'ECARTS_CONVERSION',
    report_line_code: 'ECART_CONV_ACTIF',
    label_fr: 'Ecarts de conversion actif',
    label_en: 'Translation differences - assets',
    account_prefixes: ['478'],
    source_type: 'grouped_balance',
    normal_balance_type: 'debit',
    display_sign: 'debit_positive',
    display_order: 800,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'PASSIF_ECART_CONV_PASSIF',
    report_type: 'PASSIF',
    report_section: 'ECARTS_CONVERSION',
    report_line_code: 'ECART_CONV_PASSIF',
    label_fr: 'Ecarts de conversion passif',
    label_en: 'Translation differences - liabilities',
    account_prefixes: ['479'],
    source_type: 'grouped_balance',
    normal_balance_type: 'credit',
    display_sign: 'credit_positive',
    display_order: 1301,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },

  // Formula rules. These are intentionally simple line dependencies so later batches can add
  // workbook-specific statement rows without hardcoding every subtotal inside statement engines.
  {
    id: 'CR_TOTAL_PRODUITS_EXPLOIT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'PROD_EXPLOIT',
    report_line_code: 'TOTAL_PRODUITS_EXPLOIT',
    label_fr: 'Total produits d exploitation',
    label_en: 'Total operating income',
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'formula',
    formula_type: 'custom',
    formula_expression: 'SUM(CHIFFRE_AFFAIRES,PROD_STOCKEE,PROD_IMMO,AUTRES_PROD_EXPLOIT,REPRISES_PROV)',
    display_order: 2099,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_TOTAL_CHARGES_EXPLOIT',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'CHARGES_EXPLOIT',
    report_line_code: 'TOTAL_CHARGES_EXPLOIT',
    label_fr: 'Total charges d exploitation',
    label_en: 'Total operating expenses',
    source_type: 'trial_balance',
    normal_balance_type: 'debit',
    display_sign: 'formula',
    formula_type: 'custom',
    formula_expression: 'SUM(ACHATS,SERVICES_EXT,IMPOTS_TAXES,CHARGES_PERS,AUTRES_CHARGES_EXPLOIT,DOTATIONS_AMORT)',
    display_order: 2199,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
  {
    id: 'CR_RESULTAT_EXPLOIT_FORMULA',
    report_type: 'COMPTE_RESULTAT',
    report_section: 'RESULTAT_EXPLOIT',
    report_line_code: 'RESULTAT_EXPLOIT_FORMULA',
    label_fr: 'Resultat d exploitation formule',
    label_en: 'Operating result formula',
    source_type: 'trial_balance',
    normal_balance_type: 'credit',
    display_sign: 'formula',
    formula_type: 'subtraction',
    formula_expression: 'TOTAL_PRODUITS_EXPLOIT-TOTAL_CHARGES_EXPLOIT',
    display_order: 2205,
    is_required: false,
    is_editable: false,
    allows_manual_override: true,
    is_active: true,
  },
];
